// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    id,
    user_id,
    amount,
    category,
    description,
    date,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, amount, category, description, date, created_at, updated_at
`

type CreateExpenseParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Amount      string
	Category    string
	Description sql.NullString
	Date        time.Time
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Category,
		arg.Description,
		arg.Date,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, user_id, amount, category, description, date, created_at, updated_at FROM expenses WHERE id = $1 AND user_id = $2
`

type GetExpenseByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByID, arg.ID, arg.UserID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT id, user_id, amount, category, description, date, created_at, updated_at FROM expenses WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListExpensesByUser(ctx context.Context, userID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUserAndDateRange = `-- name: ListExpensesByUserAndDateRange :many
SELECT id, user_id, amount, category, description, date, created_at, updated_at FROM expenses
WHERE user_id = $1
AND date >= $2
AND date <= $3
ORDER BY date DESC
`

type ListExpensesByUserAndDateRangeParams struct {
	UserID uuid.UUID
	Date   time.Time
	Date_2 time.Time
}

func (q *Queries) ListExpensesByUserAndDateRange(ctx context.Context, arg ListExpensesByUserAndDateRangeParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByUserAndDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Category,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses 
SET amount = $1, category = $2, description = $3, date = $4, updated_at = $5
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, amount, category, description, date, created_at, updated_at
`

type UpdateExpenseParams struct {
	Amount      string
	Category    string
	Description sql.NullString
	Date        time.Time
	UpdatedAt   sql.NullTime
	ID          uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.Amount,
		arg.Category,
		arg.Description,
		arg.Date,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Category,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
