// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Expense struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Amount      string
	Category    string
	Description sql.NullString
	Date        time.Time
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash []byte
	CreatedAt    sql.NullTime
}
